### ISSUE TITLE
Cannot find rom-build.sh

### ISSUE THREAD

**Issue by xing2387** [pixeldust-project-caf/manifest#1]
I know this project from [XDA](https://forum.xda-developers.com/project-treble/trebleenabled-device-development/9-0-pixel-dust-pie-t3862484), and want to compile it myself.
But after repo sync, i can't find the "rom-build.sh" script as the READEME said.
Need help...

**Comment by spezi77** [comment]
Fixed. Please be aware that you cannot simply compile for a new devices right away. First off, you have to "bringup" your device.

Have you ever compiled a custom ROM before? If so, then please reach out for me via telegram.

**Comment by xing2387** [comment]
> Fixed. Please be aware that you cannot simply compile for a new devices right away. First off, you have to "bringup" your device.
> 
> Have you ever compiled a custom ROM before? If so, then please reach out for me via telegram.

I had compiled CM and LineageOS, but this is the first time i touch with gsi.

I tried to send msg to you, but Telegram alert me "Sorry, you can only send messages to mutual contacts at the moment."...
I'm waiting the "Spam Info Bot" to reply to me... I will contact you as soon as i can.

BTW, can i just compile the "marlin" device which shows in the "lunch" menu, and use the system.img as gsi ?

**Comment by amarbajpai** [comment]
> > Fixed. Please be aware that you cannot simply compile for a new devices right away. First off, you have to "bringup" your device.
> > Have you ever compiled a custom ROM before? If so, then please reach out for me via telegram.
> 
> I had compiled CM and LineageOS, but this is the first time i touch with gsi.
> 
> I tried to send msg to you, but Telegram alert me "Sorry, you can only send messages to mutual contacts at the moment."...
> I'm waiting the "Spam Info Bot" to reply to me... I will contact you as soon as i can.
> 
> BTW, can i just compile the "marlin" device which shows in the "lunch" menu, and use the system.img as gsi ?

You cannot compile a GSI like this. I suggest you reading the guides for GSI compilation if you want one. One such reference is [phhusson's treble experimentations repo](https://github.com/phhusson/treble_experimentations/wiki/How-to-build-a-GSI%3F)
Also fyi there is a PixelDust-GSI already out there. If you want to test it you can look at the treble development forum on xda.
Moreover the manual lunch and make commands work fine for device specific compilation. You need not to use a script everytime. Though one such has been uploaded, you can take a look.

**Comment by xing2387** [comment]
> > > Fixed. Please be aware that you cannot simply compile for a new devices right away. First off, you have to "bringup" your device.
> > > Have you ever compiled a custom ROM before? If so, then please reach out for me via telegram.
> > 
> > 
> > I had compiled CM and LineageOS, but this is the first time i touch with gsi.
> > I tried to send msg to you, but Telegram alert me "Sorry, you can only send messages to mutual contacts at the moment."...
> > I'm waiting the "Spam Info Bot" to reply to me... I will contact you as soon as i can.
> > BTW, can i just compile the "marlin" device which shows in the "lunch" menu, and use the system.img as gsi ?
> 
> You cannot compile a GSI like this. I suggest you reading the guides for GSI compilation if you want one. One such reference is [phhusson's treble experimentations repo](https://github.com/phhusson/treble_experimentations/wiki/How-to-build-a-GSI%3F)
> Also fyi there is a PixelDust-GSI already out there. If you want to test it you can look at the treble development forum on xda.
> Moreover the manual lunch and make commands work fine for device specific compilation. You need not to use a script everytime. Though one such has been uploaded, you can take a look.

Thanks~
I had tried phhusson's GSI rom, and other GSI roms in this [list](https://github.com/phhusson/treble_experimentations/wiki/Generic-System-Image-%28GSI%29-list).
I like this PixelDust one most. But want to do some modification. Such as change some views like BackArrowView, ScreenGesturesView. So want to compile PixelDust from source.
I had read the "rom-build.sh" script. Need to setup some device configuration, like the manual way.
But i don't know how to do it, i know little about Android build system. I'm just an Android app developer... I will learn more about the build system...
