### ISSUE TITLE
build issues!!! missing wifi drivers

### ISSUE THREAD

**Issue by ahmedmoselhi** [pixeldust-project-caf/manifest#2]
external/wpa_supplicant_8/hostapd/Android.mk: error: "hostapd (EXECUTABLES android-arm64) missing lib_driver_cmd_qcwcn (STATIC_LIBRARIES androi
d-arm64)" 
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the bui
ld.
external/wpa_supplicant_8/hostapd/Android.mk: error: "hostapd_nohidl (EXECUTABLES android-arm64) missing lib_driver_cmd_qcwcn (STATIC_LIBRARIES
 android-arm64)" 
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the bui
ld.
external/wpa_supplicant_8/wpa_supplicant/Android.mk: error: "wpa_supplicant (EXECUTABLES android-arm64) missing lib_driver_cmd_qcwcn (STATIC_LI
BRARIES android-arm64)" 
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the bui
ld.
frameworks/opt/net/wifi/libwifi_hal/Android.mk: error: "libwifi-hal (SHARED_LIBRARIES android-arm64) missing libwifi-hal-qcom (STATIC_LIBRARIES
 android-arm64)" 
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the bui
ld.
frameworks/opt/net/wifi/libwifi_hal/Android.mk: error: "libwifi-hal (SHARED_LIBRARIES android-arm64) missing libcld80211 (SHARED_LIBRARIES andr
oid-arm64)" 
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the bui
ld.
frameworks/opt/net/wifi/libwifi_hal/Android.mk: error: "libwifi-hal (SHARED_LIBRARIES android-arm) missing libwifi-hal-qcom (STATIC_LIBRARIES a
ndroid-arm)" 
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the bui
ld.
frameworks/opt/net/wifi/libwifi_hal/Android.mk: error: "libwifi-hal (SHARED_LIBRARIES android-arm) missing libcld80211 (SHARED_LIBRARIES androi
d-arm)" 
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the bui
ld.
build/make/core/main.mk:976: error: exiting from previous errors.
16:37:41 ckati failed with: exit status 1

#### failed to build some targets (01:31 (mm:ss)) ####

Build failed!
when setting ALLOW_MISSING_DEPENDENCIES=true it gives dependency issue on these libs

**Comment by iraniroahn** [comment]
Hey i am facing the same issue did u find a fix for these missing blobs??

**Comment by ValentinLiu15** [comment]
I have the same issue! Anyone know how to fix it?

**Comment by spezi77** [comment]
> I have the same issue! Anyone know how to fix it?

Please check and try this new branch of our manifest.
https://github.com/pixeldust-project-caf/manifest/tree/sc-v2-caf
